# Generated by Django 5.1.15 on 2026-05-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseGoal',
            fields=[
                ('exercise_goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('target_calorie_cost', models.IntegerField()),
                ('reminder_text', models.CharField(blank=True, max_length=200)),
                ('support_quote', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseRecord',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('calorie_cost', models.IntegerField()),
                ('stress_source', models.CharField(blank=True, max_length=100)),
                ('coping_action', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
