# Generated by Django 5.1.15 on 2026-05-29 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mood_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('stress_level', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('energy_level', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('reflection', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
